// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXXQQ20UhHOwBii1ZqJv6aclam6bwzPwY',
    appId: '1:912907642951:web:db877c6e45fcb1f564e962',
    messagingSenderId: '912907642951',
    projectId: 'stajcopy',
    authDomain: 'stajcopy.firebaseapp.com',
    storageBucket: 'stajcopy.firebasestorage.app',
    measurementId: 'G-23EMZ53SFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHU_gZCoH-FfU7VlAfaK6FZEpavO11BGs',
    appId: '1:912907642951:android:49d101e883644bec64e962',
    messagingSenderId: '912907642951',
    projectId: 'stajcopy',
    storageBucket: 'stajcopy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSG7I-scQOPqR-8iyT1iTcSqPcSEmO3I',
    appId: '1:912907642951:ios:80e717cd76a2cbab64e962',
    messagingSenderId: '912907642951',
    projectId: 'stajcopy',
    storageBucket: 'stajcopy.firebasestorage.app',
    iosBundleId: 'com.example.stajcopy.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnSG7I-scQOPqR-8iyT1iTcSqPcSEmO3I',
    appId: '1:912907642951:ios:236eb7ca66e99b2764e962',
    messagingSenderId: '912907642951',
    projectId: 'stajcopy',
    storageBucket: 'stajcopy.firebasestorage.app',
    iosBundleId: 'com.example.stajcopy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXXQQ20UhHOwBii1ZqJv6aclam6bwzPwY',
    appId: '1:912907642951:web:b7fbfde47cafe95064e962',
    messagingSenderId: '912907642951',
    projectId: 'stajcopy',
    authDomain: 'stajcopy.firebaseapp.com',
    storageBucket: 'stajcopy.firebasestorage.app',
    measurementId: 'G-SZE5LKWBTD',
  );

}